"""first migration

Revision ID: 2bd3ee31a8dd
Revises: 
Create Date: 2017-06-03 17:24:28.321936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd3ee31a8dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('facebook_id', sa.String(length=255), nullable=True),
    sa.Column('linkedin_id', sa.String(length=255), nullable=True),
    sa.Column('twitter_id', sa.String(length=255), nullable=True),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], onupdate='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facebook_id'),
    sa.UniqueConstraint('linkedin_id'),
    sa.UniqueConstraint('twitter_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_info')
    op.drop_table('users')
    # ### end Alembic commands ###
